name: Process GeoSite Files

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  process-geosite-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clone specific branch and folder
      run: |
        git clone --depth 1 --branch meta https://github.com/MetaCubeX/meta-rules-dat.git

    - name: List directory for debugging
      run: |
        cd meta-rules-dat
        ls -R

    - name: Filter and clean .list files
      run: |
        cd geo/geosite
        mkdir -p ../../../../processed-files
        for file in *.list; do
          sed 's/+//g' "$file" > "../../../../processed-files/$file"
        done

    - name: Commit changes
      run: |
        cd ../../../../processed-files
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git init
        git add .
        git commit -m "Processed geosite .list files"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: processed-files