name: Process

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Run processing script
        run: |
          chmod +x other.sh
          ./other.sh

      - name: Commit and push changes
        run: |
          git checkout -b processed
          git add processed-files/*
          git commit -m "Processed files"
          git push origin processed --force
